Update flutter_cli.yml

diff --git a/.github/workflows/flutter_cli.yml b/.github/workflows/flutter_cli.yml
--- a/.github/workflows/flutter_cli.yml
+++ b/.github/workflows/flutter_cli.yml
@@ -62,13 +62,21 @@ jobs:
           cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles          
       - name: Export Options file
         env:
-         EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
+        EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
         run: |
-          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
-          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
-          
+         EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
+         echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
+
       - name: Build IPA
-        run: flutter build ipa --target lib/main_car.dart --release --export-options-plist=EXPORT_OPTS_PATH
+        run: |
+         EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
+         if [ -f "$EXPORT_OPTS_PATH" ]; then
+          flutter build ipa --target lib/main_car.dart --release --export-options-plist="$EXPORT_OPTS_PATH"
+         else
+         echo "Error: $EXPORT_OPTS_PATH does not exist."
+         exit 1
+         fi
+
 
       # - name: Export IPA
       #   env:
